// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRequest.proto

package com.xchb.xrpc.common.proto;

public final class RpcRequestProto {
  private RpcRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xchb.xrpc.common.proto.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return A list containing the paramTypes.
     */
    java.util.List<java.lang.String>
        getParamTypesList();
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return The count of paramTypes.
     */
    int getParamTypesCount();
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    java.lang.String getParamTypes(int index);
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParamTypesBytes(int index);

    /**
     * <code>repeated string params = 4;</code>
     * @return A list containing the params.
     */
    java.util.List<java.lang.String>
        getParamsList();
    /**
     * <code>repeated string params = 4;</code>
     * @return The count of params.
     */
    int getParamsCount();
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    java.lang.String getParams(int index);
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    com.google.protobuf.ByteString
        getParamsBytes(int index);

    /**
     * <code>string version = 5;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 5;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string group = 6;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 6;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>string interfaceClass = 7;</code>
     * @return The interfaceClass.
     */
    java.lang.String getInterfaceClass();
    /**
     * <code>string interfaceClass = 7;</code>
     * @return The bytes for interfaceClass.
     */
    com.google.protobuf.ByteString
        getInterfaceClassBytes();
  }
  /**
   * Protobuf type {@code com.xchb.xrpc.common.proto.RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xchb.xrpc.common.proto.RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      id_ = "";
      methodName_ = "";
      paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      version_ = "";
      group_ = "";
      interfaceClass_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RpcRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                paramTypes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              paramTypes_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                params_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              params_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              interfaceClass_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          paramTypes_ = paramTypes_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          params_ = params_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xchb.xrpc.common.proto.RpcRequestProto.internal_static_com_xchb_xrpc_common_proto_RpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xchb.xrpc.common.proto.RpcRequestProto.internal_static_com_xchb_xrpc_common_proto_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.class, com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMTYPES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList paramTypes_;
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return A list containing the paramTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_;
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @return The count of paramTypes.
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    public java.lang.String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <code>repeated string paramTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList params_;
    /**
     * <code>repeated string params = 4;</code>
     * @return A list containing the params.
     */
    public com.google.protobuf.ProtocolStringList
        getParamsList() {
      return params_;
    }
    /**
     * <code>repeated string params = 4;</code>
     * @return The count of params.
     */
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the element to return.
     * @return The params at the given index.
     */
    public java.lang.String getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated string params = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the params at the given index.
     */
    public com.google.protobuf.ByteString
        getParamsBytes(int index) {
      return params_.getByteString(index);
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 5;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 5;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 6;
    private volatile java.lang.Object group_;
    /**
     * <code>string group = 6;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 6;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERFACECLASS_FIELD_NUMBER = 7;
    private volatile java.lang.Object interfaceClass_;
    /**
     * <code>string interfaceClass = 7;</code>
     * @return The interfaceClass.
     */
    @java.lang.Override
    public java.lang.String getInterfaceClass() {
      java.lang.Object ref = interfaceClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceClass_ = s;
        return s;
      }
    }
    /**
     * <code>string interfaceClass = 7;</code>
     * @return The bytes for interfaceClass.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInterfaceClassBytes() {
      java.lang.Object ref = interfaceClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      for (int i = 0; i < paramTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paramTypes_.getRaw(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, params_.getRaw(i));
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, version_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, group_);
      }
      if (!getInterfaceClassBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, interfaceClass_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamTypesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < params_.size(); i++) {
          dataSize += computeStringSizeNoTag(params_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamsList().size();
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, version_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, group_);
      }
      if (!getInterfaceClassBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, interfaceClass_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest)) {
        return super.equals(obj);
      }
      com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest other = (com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamTypesList()
          .equals(other.getParamTypesList())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getInterfaceClass()
          .equals(other.getInterfaceClass())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamTypesCount() > 0) {
        hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypesList().hashCode();
      }
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + INTERFACECLASS_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceClass().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xchb.xrpc.common.proto.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xchb.xrpc.common.proto.RpcRequest)
        com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xchb.xrpc.common.proto.RpcRequestProto.internal_static_com_xchb_xrpc_common_proto_RpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xchb.xrpc.common.proto.RpcRequestProto.internal_static_com_xchb_xrpc_common_proto_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.class, com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.Builder.class);
      }

      // Construct using com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        methodName_ = "";

        paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = "";

        group_ = "";

        interfaceClass_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xchb.xrpc.common.proto.RpcRequestProto.internal_static_com_xchb_xrpc_common_proto_RpcRequest_descriptor;
      }

      @java.lang.Override
      public com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest getDefaultInstanceForType() {
        return com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest build() {
        com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest buildPartial() {
        com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest result = new com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.methodName_ = methodName_;
        if (((bitField0_ & 0x00000001) != 0)) {
          paramTypes_ = paramTypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.paramTypes_ = paramTypes_;
        if (((bitField0_ & 0x00000002) != 0)) {
          params_ = params_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.params_ = params_;
        result.version_ = version_;
        result.group_ = group_;
        result.interfaceClass_ = interfaceClass_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest) {
          return mergeFrom((com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest other) {
        if (other == com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.paramTypes_.isEmpty()) {
          if (paramTypes_.isEmpty()) {
            paramTypes_ = other.paramTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureParamTypesIsMutable();
            paramTypes_.addAll(other.paramTypes_);
          }
          onChanged();
        }
        if (!other.params_.isEmpty()) {
          if (params_.isEmpty()) {
            params_ = other.params_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParamsIsMutable();
            params_.addAll(other.params_);
          }
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (!other.getInterfaceClass().isEmpty()) {
          interfaceClass_ = other.interfaceClass_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 2;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 2;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 2;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 2;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamTypesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @return A list containing the paramTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParamTypesList() {
        return paramTypes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @return The count of paramTypes.
       */
      public int getParamTypesCount() {
        return paramTypes_.size();
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @param index The index of the element to return.
       * @return The paramTypes at the given index.
       */
      public java.lang.String getParamTypes(int index) {
        return paramTypes_.get(index);
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParamTypesBytes(int index) {
        return paramTypes_.getByteString(index);
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @param index The index to set the value at.
       * @param value The paramTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParamTypes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypesIsMutable();
        paramTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @param value The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypesIsMutable();
        paramTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @param values The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamTypes() {
        paramTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 3;</code>
       * @param value The bytes of the paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          params_ = new com.google.protobuf.LazyStringArrayList(params_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string params = 4;</code>
       * @return A list containing the params.
       */
      public com.google.protobuf.ProtocolStringList
          getParamsList() {
        return params_.getUnmodifiableView();
      }
      /**
       * <code>repeated string params = 4;</code>
       * @return The count of params.
       */
      public int getParamsCount() {
        return params_.size();
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param index The index of the element to return.
       * @return The params at the given index.
       */
      public java.lang.String getParams(int index) {
        return params_.get(index);
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the params at the given index.
       */
      public com.google.protobuf.ByteString
          getParamsBytes(int index) {
        return params_.getByteString(index);
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param index The index to set the value at.
       * @param value The params to set.
       * @return This builder for chaining.
       */
      public Builder setParams(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param value The params to add.
       * @return This builder for chaining.
       */
      public Builder addParams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param values The params to add.
       * @return This builder for chaining.
       */
      public Builder addAllParams(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, params_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParams() {
        params_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string params = 4;</code>
       * @param value The bytes of the params to add.
       * @return This builder for chaining.
       */
      public Builder addParamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParamsIsMutable();
        params_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 5;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 5;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 5;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 5;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 6;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 6;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 6;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 6;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object interfaceClass_ = "";
      /**
       * <code>string interfaceClass = 7;</code>
       * @return The interfaceClass.
       */
      public java.lang.String getInterfaceClass() {
        java.lang.Object ref = interfaceClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interfaceClass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string interfaceClass = 7;</code>
       * @return The bytes for interfaceClass.
       */
      public com.google.protobuf.ByteString
          getInterfaceClassBytes() {
        java.lang.Object ref = interfaceClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interfaceClass = 7;</code>
       * @param value The interfaceClass to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceClass = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterfaceClass() {
        
        interfaceClass_ = getDefaultInstance().getInterfaceClass();
        onChanged();
        return this;
      }
      /**
       * <code>string interfaceClass = 7;</code>
       * @param value The bytes for interfaceClass to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceClass_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xchb.xrpc.common.proto.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:com.xchb.xrpc.common.proto.RpcRequest)
    private static final com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest();
    }

    public static com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      @java.lang.Override
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xchb.xrpc.common.proto.RpcRequestProto.RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xchb_xrpc_common_proto_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xchb_xrpc_common_proto_RpcRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RpcRequest.proto\022\032com.xchb.xrpc.common" +
      ".proto\"\210\001\n\nRpcRequest\022\n\n\002id\030\001 \001(\t\022\022\n\nmet" +
      "hodName\030\002 \001(\t\022\022\n\nparamTypes\030\003 \003(\t\022\016\n\006par" +
      "ams\030\004 \003(\t\022\017\n\007version\030\005 \001(\t\022\r\n\005group\030\006 \001(" +
      "\t\022\026\n\016interfaceClass\030\007 \001(\tB\021B\017RpcRequestP" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xchb_xrpc_common_proto_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xchb_xrpc_common_proto_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xchb_xrpc_common_proto_RpcRequest_descriptor,
        new java.lang.String[] { "Id", "MethodName", "ParamTypes", "Params", "Version", "Group", "InterfaceClass", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
